### ISSUE TITLE
Loading one of the supplied .wav Files

### ISSUE THREAD

**Issue by vktrbhm** [3DTune-In/3dti_AudioToolkit#1]
Hello 3DTI Team,
I just installed your toolkit and I'm realy looking forward to use it in an application I'm working at the moment. To test your toolkit I frist wanted to write a simple program witch loads one of the supplied wav files and spatialize it.

I tryed to follow your example but I don't know at which point I have to load the raw data. I assume I have to load it into some buffer in the CSingleSourceDSP Class but I couldn't find a method for that. 

I would appreciate it if you could give me a quick example how I load one of the wav-files and spatialize it with your tool.

Have a nice week

**Comment by areyesl** [comment]
Hi!

Thanks for downloading and trying! the example we have included assumes that you already have an application with an audio loop and that you are able to create a buffer with the raw samples read from an audio file. 

But we are preparing now a more complete example where an audio file is read and the audio interface is managed using RTAudio. It will be ready in a couple of days, I hope. I'll post here an announcement

cheers,

Arcadio

**Comment by vktrbhm** [comment]
Hi Arcadio,

Thanks for the reply. I'm really looking forward for the new example and in the meantime I'll try to implement your api in an audio loop. This tool is awesome and it makes spatializing sound so much easier. Thank you for making it OpenSource.

Bye,

Viktor

**Comment by areyesl** [comment]
Hi, Viktor.

We have created a complete example in another repository which links to this one as a submodule, including as well some third party libraries needed to read sofa files and managing the audio interface. The idea is that it is a complete example which can be built and run, following some simple instructions.

You can find it here: https://github.com/3DTune-In/3dti_AudioToolkit_Examples

I hope this clarifies the use of the library. 

Cheers,

Arcadio

**Comment by areyesl** [comment]
I close this issue as I understand it is solved. If anyone has similar problems, please, comment on it or open another one.
