### ISSUE TITLE
real time question

### ISSUE THREAD

**Issue by Lixuya** [3DTune-In/3dti_AudioToolkit#10]
When I was doing brir processing, 20 seconds of audio processing took 30 minutes, which could not be processed in real time but your test app could be processed in real time, why？

**Comment by areyesl** [comment]
Hi! We would need more information about how you are using the toolkit to be able to help. 

Are you compiling in Release or Debug mode? Please, consider that the toolkit process is quite heavy and performace in debug mode is very low. 
Which is your operating system? 
Which BRIR are you using? are you using the same BRIR in your application and the test app? Consider tht processing time depends very much on the BRIR length.

Best regards
Arcadio

**Comment by Lixuya** [comment]
The vstudio debug project I compiled on win10, the code is as follows:

``
#include "mian.h"
#include <cstdio>
#include <cstring>
#include <windows.h>

FILE *fp_input = fopen("02.Hotel.pcm", "rb");
FILE *fp_output = fopen("out.pcm", "wb");
bool bEnableReverb=true;
int iBufferSize=512;

int main() {
	// Core setup
	Common::TAudioStateStruct audioState;	    // Audio State struct declaration
	audioState.bufferSize = iBufferSize;			// Setting buffer size and sample rate
	audioState.sampleRate = 44100;       //44100;
	myCore.SetAudioState(audioState);		      // Applying configuration to core
	myCore.SetHRTFResamplingStep(15);		      // Setting 15-degree resampling step for HRTF

	ERRORHANDLER3DTI.SetVerbosityMode(VERBOSITYMODE_ERRORSANDWARNINGS);
	ERRORHANDLER3DTI.SetErrorLogStream(&std::cout, true);
	// Listener setup
	listener = myCore.CreateListener();								 // First step is creating listener
	Common::CTransform listenerPosition = Common::CTransform();		 // Setting listener in (0,0,0)
	listenerPosition.SetPosition(Common::CVector3(0, 0, 0));
	listener->SetListenerTransform(listenerPosition);
	listener->DisableCustomizedITD();								 // Disabling custom head radius

																	 /* HRTF can be loaded in either SOFA (more info in https://sofacoustics.org/) or 3dti-hrtf format.
																	 These HRTF files are provided with 3DTI Audio Toolkit. They can be found in 3dti_AudioToolkit/resources/HRTF */
	HRTF::CreateFrom3dti("hrtf.3dti-hrtf", listener);			 // Comment this line and uncomment next lines to load the default HRTF in SOFA format instead of in 3dti-hrtf format
																 /*
																 bool bSpecifiedDelays;
																 HRTF::CreateFromSofa("hrtf.sofa", listener, bSpecifiedDelays);
																 */

																 // Environment setup
	environment = myCore.CreateEnvironment();									// Creating environment to have reverberated sound
	environment->SetReverberationOrder(TReverberationOrder::BIDIMENSIONAL);		// Setting number of ambisonic channels to use in reverberation processing
	//BRIR::CreateFromSofa("../../../3dti_AudioToolkit/resources/BRIR/SOFA/3DTI_BRIR_large_44100Hz.sofa", environment);
	//BRIR::CreateFromSofa("brir.sofa", environment);
	BRIR::CreateFrom3dti("../../../3dti_AudioToolkit/resources/BRIR/3DTI/3DTI_BRIR_large_44100Hz.3dti-brir", environment);

	// Speech source setup
	sourceLeft = myCore.CreateSingleSourceDSP();										 // Creating audio source
	//LoadWav(samplesVectorSpeech, "speech.wav");											 // Loading .wav file
	Common::CTransform sourceSpeechPosition = Common::CTransform();
	sourceSpeechPosition.SetPosition(Common::CVector3(2, 0, 0));						 // Setting source in x=0,y=2,z=0 (on the left)
	sourceLeft->SetSourceTransform(sourceSpeechPosition);
	sourceLeft->SetSpatializationMode(Binaural::TSpatializationMode::HighQuality);	//HighPerformance vs HighQuality // Choosing high quality mode for anechoic processing
	sourceLeft->DisableNearFieldEffect();												 // Audio source will not be close to listener, so we don't need near field effect
	sourceLeft->EnableAnechoicProcess();												 // Setting anechoic and reverb processing for this source
	sourceLeft->EnableDistanceAttenuationAnechoic();

	// Steps source setup
	sourceRight = myCore.CreateSingleSourceDSP();										 // Creating audio source
	//LoadWav(samplesVectorSteps, "steps.wav");											   // Loading .wav file
	Common::CTransform sourceStepsPosition = Common::CTransform();
	sourceStepsPosition.SetPosition(Common::CVector3(-2, 0, 0));						 // Setting source in (-3,-10,-10)
	sourceRight->SetSourceTransform(sourceStepsPosition);
	sourceRight->SetSpatializationMode(Binaural::TSpatializationMode::HighQuality);		 // Choosing high quality mode for anechoic processing
	sourceRight->DisableNearFieldEffect();												 // Audio source will not be close to listener, so we don't need near field effect
	sourceRight->EnableAnechoicProcess();												   // Setting anechoic and reverb processing for this source
	sourceRight->EnableDistanceAttenuationAnechoic();
	sourcePosition = sourceStepsPosition;												 // Saving initial position into source position to move the steps audio source later on

																						 // Declaration and initialization of stereo buffer
	outputBufferStereo.left.resize(iBufferSize);
	outputBufferStereo.right.resize(iBufferSize);
	inputbuff = new short[iBufferSize*2];
	outputbuff = new short[iBufferSize*2];
	while (iBufferSize*2 == fread(inputbuff, sizeof(short), iBufferSize*2, fp_input))
	{
		outputBufferStereo.left.Fill(iBufferSize, 0.0f);
		outputBufferStereo.right.Fill(iBufferSize, 0.0f);

		// Getting the processed audio
		audioProcess(outputBufferStereo, iBufferSize);
		for (int i = 0; i < iBufferSize; i++)
		{
			//outputbuff[2 * i] =outputBufferStereo.left[i];
			//outputbuff[2 * i+1] = (outputBufferStereo.right[i]);
			int tmp1 = outputBufferStereo.left[i]*32767;
			if (tmp1 > 32767)
				outputbuff[2 * i] = 32767;
			else if (tmp1 < -32768)
				outputbuff[2 * i] = -32768;
			else
				outputbuff[2 * i] = tmp1;
			int tmp2 = outputBufferStereo.right[i] * 32767;
			if (tmp2 > 32767)
				outputbuff[2 * i+1] = 32767;
			else if (tmp2 < -32768)
				outputbuff[2 * i+1] = -32768;
			else
				outputbuff[2 * i+1] = tmp2;
		}
		fwrite(outputbuff, sizeof(short), iBufferSize*2, fp_output);
	}
}
void audioProcess(Common::CEarPair<CMonoBuffer<float>> & bufferOutput, int uiBufferSize)
{
	// Declaration, initialization and filling mono buffers
	CMonoBuffer<float> letfInput(uiBufferSize);	
	CMonoBuffer<float> rightInput(uiBufferSize);
	for (int i = 0; i < iBufferSize; i++)
	{
		letfInput[i] = (float)inputbuff[2 * i]/32767;
		rightInput[i] = (float)inputbuff[2*i+1]/32767;
	}
	
		// Declaration of stereo buffer
		Common::CEarPair<CMonoBuffer<float>> bufferProcessed;

		// Anechoic process of speech source
		sourceLeft->SetBuffer(letfInput);
		sourceLeft->ProcessAnechoic(bufferProcessed.left, bufferProcessed.right);

		// Adding anechoic processed speech source to the output mix

		bufferOutput.left += bufferProcessed.left;
		bufferOutput.right += bufferProcessed.right;

		// Anechoic process of steps source
		sourceRight->SetBuffer(rightInput);
		sourceRight->ProcessAnechoic(bufferProcessed.left, bufferProcessed.right);

		// Adding anechoic processed steps source to the output mix
		bufferOutput.left += bufferProcessed.left;
		bufferOutput.right += bufferProcessed.right;
	

	// Declaration and initialization of separate buffer needed for the reverb
	Common::CEarPair<CMonoBuffer<float>> bufferReverb;

	// Reverberation processing of all sources
	if (bEnableReverb) {
		environment->ProcessVirtualAmbisonicReverb(bufferReverb.left, bufferReverb.right);
		// Adding reverberated sound to the output mix
		bufferOutput.left += bufferReverb.left;
		bufferOutput.right += bufferReverb.right;
	}
	
}

``

**Comment by Lixuya** [comment]
I have tried several brir files

**Comment by areyesl** [comment]
Please, try in Release mode. 

> The vstudio debug project I compiled on win10, the code is as follows:

**Comment by Lixuya** [comment]
I tried Release mode，It takes 1.5 minutes to process 40s audio，Faster than debug

**Comment by areyesl** [comment]
Great! That makes sense. 
If it is still too slow for you, the only solution is to use a shorter BRIR or a faster machine :). We use in the testapp by default a short BRIR for this reason.

Best Regards
Arcadio
