### ISSUE TITLE
Ear-blasting clipping is in dire need of a limiter/normalizer

### ISSUE THREAD

**Issue by ThreeDeeJay** [3DTune-In/3dti_AudioToolkit#18]
I've lost count of the amount of jump scares I've had with this app, due to how obscenely loud it can get with barely any sort of safeguards like a limiter/normalizer to prevent clipping. 
DirectSound mode seems to apply a soft limiter but still clipping and pops can be heard, but ASIO? It'd break the sound barrier and my eardrums if I let it. 
The Calibration option doesn't seem to do anything either (nothing plays and even when setting system volume to 1, the audio can still easily clip)
It happens if the sound clip is too loud, if its volume slider isn't low enough (sometimes not even the lowest is enough), if it's too close or even when using [certain](https://sofacoustics.org/data/database/scut/SCUT_KEMAR_radius_all.sofa) HRTF SOFA files at any point that's not way outside the circle.

![image](https://user-images.githubusercontent.com/71472458/198589565-c017d951-946b-4acc-84bc-5b6e8577d016.png)

This happens way too often, and I can't help but think there's something I'm missing because I can't be the first one to point out the elephant in the room or if it's related to Windows, ASIO or something more specific to my case. But even if there is a crucial step, there should a clear warning in the app because someone who's none the wiser could hit play with their headphones on full blast and get a free ticket to Tinnitus or hear the real thing without the need of a simulation 😅

**Comment by lpicinali** [comment]
Hello, and thanks for your comment.
We are aware of the risk to reproduce potentially loud signals, and we have discussed several times within the team whether to allow this or not. The 3D Tune-In Toolkit has been created to simulate what happens in real life: if you listen to someone speaking with a normal voice, at 20cm of distance, you'll notice that the level is indeed dangerously high, and this is what we are simulating. 
We though very much understand the risks you mention, and we'll therefore include in the next release a few measures to avoid this in the first instance (i.e. we'll disable by defauls the increase/decrease of level with distance for both direct path and reverb components - of course both these controls can be re-enabled by the user, and when doing so a warning message will appear on the app), and mitigate the effect (i.e. we'll add a limiter at the end of the audio chain).
We'll let you know when these have been implemented.
Thanks again for your contribution!

**Comment by ThreeDeeJay** [comment]
I see, that's completely understandable and thank you for considering a limiter because I really like this application.
and I apologize if I came across as rude, it's just that I'm particularly protective of my hearing so I try my best to avoid extremely loud noises.

**Comment by lpicinali** [comment]
Don't worry - we very much understand!

**Comment by areyesl** [comment]
Hi, 3DJ!
He have just released the latest version and we have included some safeguard mechanisms to prevent too loud sounds:

- Attenuation by distance is now disabled when the application starts (both anechoic and reverb paths). You can enable them, but then, a warning message will apear (only once).
- When the level delivered is louder than 0dBfs, the application stops and shows a warning. You can then disable this warning or keep it. 

Finally, just a comment about the calibration option which you mentioned. This calibration has no effect on the overall sound level. It is used just to let the app know which is the correspondence between the digital level (fs) and the real level (SPL). This is needed for the correct function of the Hearing Aid and the Hearing Loss simulator, which need a reference to the actual SPL, but is not used by any other process.

I hope the app is safer now. Thanks for your comments!

Best regards
Arcadio

**Comment by ThreeDeeJay** [comment]
Thank you so much!
it's working as expected so far. and even the problematic SOFA I mentioned loads fine, too. 😄
