### ISSUE TITLE
Toolkit crashing (but no logs?)

### ISSUE THREAD

**Issue by hyve9** [3DTune-In/3dti_AudioToolkit#22]
Every time after I open the program, after about 5 minutes, it crashes for no apparent reason. Here's what I see in my terminal:

```
$ BiTA  
[verbose] App built date: Oct 20 2020 | time: 10:17:13

[verbose] 
List of devices availables: 

ID: 3 Name: Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 1 Output
ID: 4 Name: Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 2 Output
ID: 5 Name: Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 3 Output


[verbose] Device selected : ID: 3  Name: Alder Lake PCH-P High Definition Audio Controller HDMI / DisplayPort 1 Output.

[verbose] HL Setup Simulator postponed until activation
[verbose] nearDistanceILD Near Field Effect simulation file NearFieldCompensation_ILD_44100.3dti-ild has been loaded successfully.
[verbose] nearDistanceILD Spatialization simulation file HRTF_ILD_44100.3dti-ild has been loaded successfully
[verbose] HRTF loaded from SOFA file ../../../../../usr/bin/BiTA-dir/data/./HRTF/SOFA/3DTI_HRTF_D2_256s_44100Hz.sofa with length 256

[verbose] BRIR loaded from SOFA file ../../../../../usr/bin/BiTA-dir/data/./BRIR/SOFA/3DTI_BRIR_Trapezoid_44100Hz_3D.sofa with length 39700

[verbose] Starting HL Setup, this may take a while..... BUFFER SIZE: 512
[verbose] HL Setup finished
[verbose] OpenDialog: User selected a file: 
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
[warning] ofRtAudioSoundStream: stream over/underflow detected
zsh: killed     BiTA
```
I get the `zsh: killed` message with no information as to why the program was killed. Where can I look?
I assumed that the over/underflow messages were benign but they may not be. I am using pipewire-jack for realtime audio control.

**Comment by areyesl** [comment]
Hi, hyve9,
I see you are using the Linux version. Unfortunately, we had an issue with Linux due to the version we use of OpenFrameworks. We have tested it only in Ubuntu 18.04. In fact, we know there are some problems with versions later than 18.04 and I had no time to update the Linux version of BiTA to a newer version of OF to be compatible with newer versions of Ubuntu. Maybe that's related with the crash you have.

Are you using Ubuntu? Can you tell us which version?

Arcadio

**Comment by hyve9** [comment]
Hi - I'm using Arch Linux, I have had to update a few of the required libraries as they had no equivalents in Arch. I have replaced 
- gir with gobject-introspection 
- libssl with openssl
- jack2 with pipewire-jack
- removed gtk (in favor of gtk2 and gtk3). 

Part of me wonders if the gtk(1) missing is why it is crashing, but at the very least I would expect some error message indicating something to that effect. Instead  the `killed` message makes me think the process was killed intentionally. I am mainly just looking for more areas to troubleshoot. Would it make sense to build from source instead of using the pre-built binaries (the deb package)? Are there instructions on building from source?

**Comment by areyesl** [comment]
Hi, 
The Binaural Test App (BiTA) has been tested only in Ubuntu. Looking at the log you have attached, we would say that something in OpenFrameworks, probably in the audio libraries, is not working properly and is killing the application (but not our code). 

BiTA was developed just to allow the community to quickly test all the features of the library, but it is not open source. What you can do is to try to build some of the basic examples we have opensource. there are a couple of examples using OpenFrameworks:  [https://github.com/3DTune-In/3dti_AudioToolkit_Examples](https://github.com/3DTune-In/3dti_AudioToolkit_Examples). 

Hope that helps.
