### ISSUE TITLE
Link to the latest release of the Windows test app doesn't work

### ISSUE THREAD

**Issue by rapolasd** [3DTune-In/3dti_AudioToolkit#26]
In the latest release ([AudioToolkit v2.0 M20221031](https://github.com/3DTune-In/3dti_AudioToolkit/releases/tag/M20221031)), the link to the Windows version of the 3DTI test app ([3D Tune-In Toolkit Test app v4.1.0 for Windows](https://github.com/3DTune-In/3dti_AudioToolkit/releases/download/M20221031/BiTA.V4.1.0.D20231102.Tk-v2.0.M20231102.WIN.zip)) doesn't work (it shows up as not found).

**Comment by areyesl** [comment]
Fixed.
