### ISSUE TITLE
cmake build example

### ISSUE THREAD

**Issue by NielsHygum** [3DTune-In/3dti_AudioToolkit#6]
Hi,

I need to use a binaural audio library for android. Would be awesome if you could make a build example for android using cmake :)

**Comment by areyesl** [comment]
Hi, Niels!

Glad to see you are interested in the 3DTI Toolkit. Unfortunately, we don't have resources at this moment to prepare examples for Android. If you manage to create any yourself, please let us know - it would be fantastic if you shared them with us.

Best
Arcadio
