### ISSUE TITLE
Is there any way to read SOFA or 3DTi from memory？

### ISSUE THREAD

**Issue by Maggie-Jing** [3DTune-In/3dti_AudioToolkit#7]
Hi,
Is there any way to read SOFA or 3DTi from memory?

**Comment by areyesl** [comment]
Hi, Maggie!
Yes! In fact, that's what the modules in the 3dti_ResourceManage folder do. They read SOFA or 3DTI files and store them in memory using Libsofa and Cereal respectively. Then, they are transferred to CHRTF and CBRIR classes. But you can transfer them by your own using `void BeginSetup(int32_t _HRIRLength, float _distance);` `void AddHRIR(float azimuth, float elevation, THRIRStruct && newHRIR);` and `void EndSetup();` (in the case of HRTF). This way, you are able to create from memory a full HRTF transfering each impulse respones one by one.
The idea behind this is that you don't need third party libraries, like Libsofa and Cereal to use the toolkit if you are able to provide the impuse responses of HRTF (and BRIR if needed).

Best,

Arcadio
